# The URL the site will be built for
base_url = "https://thelowesttype.github.io"
title = "The Lowest Type"
description = "The Very Best of the Humans"

# The site theme to use.
theme = "adidoks"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true
feed_filename = "rss.xml"

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"}, # Basic definition: no feed or pagination
  {name="tags", rss=true},
]

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
author = "Saksham Sharma"
github = "https://github.com/codeck313"
twitter = "https://twitter.com/codeck313"
youtube = "https://www.youtube.com/channel/UC7BLVR5OvHzaD7utOEuk94g"
email = "sakshamsharma.ec19@rvce.edu.in"

# If running on netlify.app site, set to true
is_netlify = true

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "Easily formed"


# Set date format in blog publish metadata
timeformat = "%d %m %Y" # e.g. June 14, 2021
timezone = "America/New_York"

# Edit page on reposity or not
edit_page = false
docs_repo = "https://github.com/codeck313/"
repo_branch = "main"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
# TODO
image = "https://i.ibb.co/bjtPvfL/logo.png"
twitter_site = "codeck313"
twitter_creator = "codeck313"
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-doks.png"
twitter = "https://twitter.com/codeck313"
linked_in = ""
github = "https://github.com/codeck313"
section = "blog" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false


# Menu items
[[extra.menu.main]]
name = "Projects"
section = "projects"
url = "/projects/"
weight = 10

[[extra.menu.main]]
name = "Blog"
section = "blog"
url = "/blog/"
weight = 20

#[[extra.menu.main]]
#name = "Resume"
#section = "resume"
#url = "/aboutme/Saksham_Sharma_CV.pdf"
#weight = 20

[[extra.menu.main]]
name = "About"
section = "aboutme"
url = "/aboutme/"
weight = 20


[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/codeck313"
weight = 20

[[extra.menu.social]]
name = "Linkdin"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>'
url = "https://linkedin.com/in/saksham-sharma-98678ab7"
weight = 20

[[extra.menu.social]]
name = "Instagram"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.5" y2="6.5"></line></svg>'
url = "https://instagram.com/c0deck313"
weight = 20



# Footer contents
[extra.footer]
info = 'Follow me on <a href="https://github.com/codeck313" target="_blank">Github</a>, <a href="https://linkedin.com/in/saksham-sharma-98678ab7" target="_blank">Linkedin</a> and <a href="https://instagram.com/c0deck313" target="_blank">Instagram</a>'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10

